export type Project = {
  id: number;
  title: string;
  slug: string;
  price: number;
  displayPrice: string;
  image: string;
  images?: string[];  // up to 3 images for the card carousel
  status: string;
  bedrooms: number;
  location: string;
  PlotArea?: string;
  address: string;
  featured?: boolean;
  description: string;
  zone: "East" | "West";
};

export const projects: Project[] = [
  {
    id: 1,
    title: "Aaradhana Sky 2",
    slug: "aaradhana-sky-2",
    price: 260000,
    displayPrice: "₹ 26 Lakh",
    image: "/images/east/AARADHANA_2.jpeg",
    images: ["/images/east/AARADHANA_2.jpeg", "/images/east/Anusthan.jpeg", "/images/east/Avalon-DHS.jpeg"],
    status: "For Sale",
    bedrooms: 2,
    location: "Ahmedabad",
    PlotArea: "110 SQ.YRD & 115 SQ.YRD",
    address: "Beside Avadh Green Bungalows, Narol-Aslali Highway, Behind Pooja Farm Road, Narol, Ahmedabad - 382405",
    featured: true,
    description: "Aaradhana Sky 2 offers luxurious 2 BHK flats in Narol, Ahmedabad with FREE furniture and modular kitchen. Limited project of only 56 premium units designed with modern amenities and quality construction for comfortable living.",
    zone: "East"
  },
  {
    id: 2,
    title: " Anushtan Bungalows",
    slug: "anushtan-bungalows",
    price: 12000000,
    displayPrice: "₹ 1.20 Cr",
    image: "/images/east/Anusthan.jpeg",
    images: ["/images/east/Anusthan.jpeg", "/images/east/AARADHANA_2.jpeg", "/images/east/Avalon-DHS.jpeg"],
    status: "For Sale",
    bedrooms: 4,
    location: "Ahmedabad",
    PlotArea: "150 Sq. Yards",
    address: " B/h Parijat Vishwas, Nr. Vatva-Gamdi Circle, S.P.Ring Road, Ahmedabad-382440.",
    featured: true,
    description: "Anushtan Bungalows offers a complete modern lifestyle and a true sanctuary of luxury and comfort. Located near Vatva-Gamdi Circle, this exclusive residential project presents bigger and better 4 BHK homes designed for premium living, fresh open air, and an elevated lifestyle experience.",
    zone: "East"
  },
  {
    id: 3,
    title: "Avalon DHS Floora",
    slug: "avalon-dhs-floora",
    price: 2065000,
    displayPrice: "₹ 20.65 Lakh Onwards",
    image: "/images/east/Avalon-DHS.jpeg",
    images: ["/images/east/Avalon-DHS.jpeg", "/images/east/Anusthan.jpeg", "/images/east/Eleven.jpeg"],
    status: "Ready Possession",
    bedrooms: 2,
    location: "Vatva, Ahmedabad",
    PlotArea: "1.5 BHK, 2 BHK & 2.5 BHK Options Available",
    address: "Avalon DHS Floora, Beside Avalon Park, Near Ayodhya Apartment, Near Water Tank, Vatva-Gamdi Road, Vatva, Ahmedabad - 382445",
    featured: true,
    description: "Experience the WOW factor at Avalon DHS Floora, Vatva. Ready possession 1.5, 2 & 2.5 BHK homes starting from ₹20.65 Lakh with FREE fixed furniture, 100% loan assistance, modern amenities, 24x7 security, lifts, parking, CCTV surveillance, fire safety and premium construction quality.",
    zone: "East"
  },
  {
    id: 4,
    title: "Eleven 04 Homes",
    slug: "eleven-04-homes",
    price: 3265000,
    displayPrice: "₹ 32.65 Lakh Onwards",
    image: "/images/east/Eleven.jpeg",
    images: ["/images/east/Eleven.jpeg", "/images/east/Sahajanand-harmony.jpeg", "/images/east/Sanrise-home.jpeg"],
    status: "For Sale",
    bedrooms: 2,
    location: "New Vatva, Ahmedabad",
    PlotArea: "2 BHK (141 Sq.Yrd) & 3 BHK (160 Sq.Yrd)",
    address: "Near Krishnam International School, S.P. Ring Road, New Vatva, Ahmedabad - 382445, Gujarat",
    featured: true,
    description: "Eleven 04 Homes offers spacious and luxurious 2 & 3 BHK flats in New Vatva, Ahmedabad. Starting from ₹32.65 Lakh, this premium residential project features large room sizes, modern amenities, solar-powered common services, 24x7 security, basement parking, personal EV charging points, and vastu-compliant design. Sample flat ready with early possession and special booking discounts available.",
    zone: "East"
  },
  {
    id: 5,
    title: "Sahajanand Exotica",
    slug: "sahajanand-exotica",
    price: 3699000,
    displayPrice: "₹ 36.99 Lakh Onwards",
    image: "/images/east/sahajanand-exotica.jpeg",
    images: ["/images/east/sahajanand-exotica.jpeg", "/images/east/Sahajanand-harmony.jpeg", "/images/west/harnav_lavish2.avif"],
    status: "Ready Possession",
    bedrooms: 2 & 3,
    location: "Ghodasar, South East Ahmedabad",
    PlotArea: "131 - 165 Sq. Yards (131, 132, 134, 135, 142, 151, 165 Options)",
    address: "FP No. 16/1, TPS No. 88, Opp. Zeal Apartment, 80 Ft Road, Near Nigam Society, Vatva, South East Ahmedabad - 382440, Gujarat",
    featured: true,
    description: "Sahajanand Exotica offers premium 2 & 3 BHK luxurious flats in Ghodasar, Ahmedabad. A ready possession project with B.U. permission, featuring only 70 exclusive flats, modern amenities, solar-powered common services, basement parking, gym, community hall, and excellent AMTS connectivity. Book your dream home today with just ₹51,000.",
    zone: "East"
  },
  {
    id: 6,
    title: "Sahajanand Harmony",
    slug: "sahajanand-harmony",
    price: 2751000,
    displayPrice: "₹ 27.51 Lakh Onwards",
    image: "/images/east/Sahajanand-harmony.jpeg",
    images: ["/images/east/Sahajanand-harmony.jpeg", "/images/east/sahajanand-exotica.jpeg", "/images/east/sona-sidhhi.jpeg"],
    status: "Ready Possession",
    bedrooms: 2,
    location: "New Vatva, Ahmedabad",
    PlotArea: "118, 120, 125, 131 Sq. Yards",
    address: "Beside Ayodhya Apartment, Vatva-Gamdi Road, S.P. Ring Road, New Vatva, Ahmedabad, Gujarat",
    featured: true,
    description: "Sahajanand Harmony offers luxurious 2 BHK ready possession flats in New Vatva, Ahmedabad. A premium 100 ft road-touch scheme with only 84 exclusive units, B.U. permission, FREE fixed furniture and modular kitchen. Starting from ₹27.51 Lakh with just ₹51,000 booking amount. Solar-powered common services ensure low maintenance living.",
    zone: "East"
  },
  {
    id: 7,
    title: "Swara Premium Bungalows",
    slug: "swara-premium-bungalows",
    price: 0,
    displayPrice: "Price On Request",
    image: "/images/east/Swara.jpeg",
    images: ["/images/east/Swara.jpeg", "/images/east/Anusthan.jpeg", "/images/east/sahajanand-exotica.jpeg",],
    status: "For Sale",
    bedrooms: 4,
    location: "Narol-Aslali, Ahmedabad",
    PlotArea: "120 to 313 Sq. Yards",
    address: "Near Bharat Petrol Pump, Narol-Aslali Highway Touch, Aslali Bridge Service Road, Narol-Aslali, Ahmedabad",
    featured: true,
    description: "Swara by Swarg Bhagirath presents 4 BHK premium bungalows near Ring Road, Narol-Aslali, Ahmedabad. A thoughtfully planned scheme with only 63 exclusive units spread across 9600 sq. yards land, offering 53% open space, 25 ft wide internal roads, personal solar panels, private terrace gardens, and modern lifestyle amenities. Experience luxury, comfort, and fresh living in New Ahmedabad.",
    zone: "East"
  },
  {
    id: 8,
    title: "Sona Siddhi Premium Living",
    slug: "sona-siddhi-premium-living",
    price: 2051000,
    displayPrice: "₹ 20.51 Lakh* Onwards",
    image: "/images/east/sona-sidhhi.jpeg",
    images: ["/images/east/sona-sidhhi.jpeg", "/images/east/Sanrise-home.jpeg", "/images/east/Eleven.jpeg"],
    status: "For Sale",
    bedrooms: 1,
    location: "New Vatva, Ahmedabad",
    PlotArea: "Large Room Size Flats",
    address: "100 Ft Road, Near Osiya Hyper Mart, Vatva-Ropda Road, New Vatva, Ahmedabad - 382440",
    featured: true,
    description: "Sona Siddhi Premium Living offers ready possession 1 & 2 BHK apartments with B.U. permission near S.P. Ring Road, New Vatva, Ahmedabad. Limited flats available with FREE fixed furniture, modern amenities, large room sizes, and excellent connectivity. A perfect blend of comfort, convenience, and affordability starting from ₹20.51 Lakh onwards.",
    zone: "East"
  },
  {
    id: 9,
    title: "Sunrise Homes 1",
    slug: "sunrise-homes-1",
    price: 2025000,
    displayPrice: "₹ 20.25 Lakh* Onwards",
    image: "/images/east/Sanrise-home.jpeg",
    images: ["/images/east/Sanrise-home.jpeg", "/images/east/sona-sidhhi.jpeg", "/images/east/Eleven.jpeg"],
    status: "For Sale",
    bedrooms: 1,
    location: "New Vatva, Ahmedabad",
    PlotArea: "85 / 90 SQ.YRD",
    address: "New Vatva, Ahmedabad, Gujarat",
    featured: true,
    description: "Sunrise Homes 1 offers super spacious 1 BHK flats in New Vatva with FREE fixed furniture and modular kitchen. Ready possession homes designed for comfort, security, and convenience at a prime location. Starting from ₹20.25 Lakh onwards with maximum loan assistance available.",
    zone: "East"
  },
  {
    id: 10,
    title: "Omkar Enclave",
    slug: "omkar-enclave",
    price: 7000000,
    displayPrice: "₹ 70 Lakh* Onwards",
    image: "/images/west/omkar.jpeg",
    images: ["/images/west/omkar.jpeg", "/images/west/subh-green.jpeg", "/images/west/vivaan_orbit1.avif"],
    status: "For Sale",
    bedrooms: 3,
    location: "Ranip, Ahmedabad",
    PlotArea: "2 BHK - 165 Sq.Yrd | 3 BHK - 195 Sq.Yrd",
    address: "Behind Ranip Bus Terminal, Radha Swami Road, Ranip, Ahmedabad - 382480",
    featured: true,
    description: "Omkar Enclave offers premium 2 & 3 BHK luxury flats in the heart of Ranip, Ahmedabad. Strategically located near D-Mart, PVR, Ranip ST Bus Terminal, BRTS, RTO Circle, and Sabarmati Railway Station. Designed for modern urban living with landscaped gardens, mini club house, gated security, and premium amenities. Starting from ₹70 Lakh onwards with limited units available.",
    zone: "West"
  },
  {
    id: 11,
    title: "Shubh Greens",
    slug: "shubh-greens",
    price: 7000000,
    displayPrice: "₹ 70 Lakh* Onwards",
    image: "/images/west/subh-green.jpeg",
    images: ["/images/west/subh-green.jpeg", "/images/west/omkar.jpeg", "/images/west/royal-crown1.avif"],
    status: "For Sale",
    bedrooms: 3,
    location: "Zundal, Ahmedabad",
    PlotArea: "210 Sq. Yards",
    address: "Shubh Greens, Behind Lubi Corporate, Near Vaishnodevi Circle, S.P. Ring Road, Ahmedabad - 382470",
    featured: true,
    description: "Shubh Greens offers premium 3 BHK ready-to-move flats in Zundal, Ahmedabad. Limited to just 70 exclusive units with only 3 flats per floor, this project ensures privacy, comfort, and modern luxury living. Located near Vaishnodevi Circle and S.P. Ring Road, it provides excellent connectivity along with premium amenities and high-quality construction. Starting from ₹70 Lakh onwards.",
    zone: "West"
  },
  {
    id: 12,
    title: "Royal Crown",
    slug: "royal-crown",
    price: 7000000,
    displayPrice: "₹70 L - ₹75 L",
    image: "/images/west/royal-crown1.avif",
    images: [
      "/images/west/royal-crown1.avif",
      "/images/west/royal-crown2.avif",
      "/images/west/royal-crown3.avif"
    ],
    status: "Ready to Move",
    bedrooms: 3,
    location: "Zundal, North West, Ahmedabad",
    PlotArea: "210 Sq. Yards",
    address: "Shubh Greens, Behind Lubi Corporate, Near Vaishnodevi Circle, S.P. Ring Road, Ahmedabad - 382470",
    featured: true,
    zone: "West",
    description:
      "Experience comfortable living at Royal Crown, located in the prime area of Vaishnodevi. This 2 BHK residence spans 158 sq. yd., offering well-planned spaces and modern design. Available at ₹69.70 Lakhs, it is a perfect choice for families looking for a blend of affordability and elegance."
  },
  {
    id: 13,
    title: "Harnav Lavish",
    slug: "harnav-lavish",
    price: 5280000,
    displayPrice: "₹52.80 L - ₹63 L",
    image: "/images/west/harnav_lavish2.avif",
    images: [
      "/images/west/harnav_lavish1.avif",
      "/images/west/harnav_lavish2.avif",
      "/images/west/harnav_lavish3.avif"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "Zundal, North West, Ahmedabad",
    address: "Harnav Lavish, Zundal, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Harnav Lavish offers thoughtfully designed 2 BHK apartments in Zundal, Ahmedabad. With multiple size options ranging from 150 to 165 sq. yards, the project caters to diverse family needs. Priced between ₹52.80 Lakh to ₹63 Lakh, it combines affordability with modern amenities, making it an ideal choice for homebuyers seeking comfort, connectivity, and value."
  },

  {
    id: 14,
    title: "KB Royal",
    slug: "kb-royal",
    price: 8700000,
    displayPrice: "₹87 L",
    image: "/images/west/kb_royal1.avif",
    images: [
      "/images/west/kb_royal1.avif",
      "/images/west/kb_royal2.avif",
      "/images/west/kb_royal3.avif"
    ],
    status: "Ready to Move",
    bedrooms: 3,
    location: "Zundal, North West, Ahmedabad",
    PlotArea: "210 Sq. Yards",
    address: "KB Royal, Zundal, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Experience premium living at KB Royal, located in the well-developed area of Zundal, Ahmedabad. This spacious residence offers a 210 sq. yard layout, designed to provide comfort, functionality, and modern lifestyle living. Priced at ₹87 Lakhs, it is an excellent choice for families seeking a peaceful environment with good connectivity and quality construction."
  },
  {
    id: 15,
    title: "Vivan Orbit",
    slug: "vivan-orbit",
    price: 6350000,
    displayPrice: "₹63.50 L",
    image: "/images/west/vivaan_orbit1.avif",
    images: [
      "/images/west/vivaan_orbit1.avif",
      "/images/west/vivaan_orbit2.avif",
      "/images/west/vivaan_orbit3.avif"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "Zundal, North West, Ahmedabad",
    PlotArea: "167 Sq. Yards",
    address: "Vivan Orbit, Zundal, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Vivan Orbit offers well-designed 2 BHK apartments in the fast-growing locality of Zundal, Ahmedabad. With a spacious 167 sq. yard layout, this project is ideal for modern families seeking comfort and functionality. Priced at ₹63.50 Lakhs, it provides a perfect balance of affordability, connectivity, and quality living."
  },
  {
    id: 16,
    title: "Swastik Square",
    slug: "swastik-square",
    price: 5732000,
    displayPrice: "₹57.32 L - ₹62.60 L",
    image: "/images/west/swastik-square1.jpg",
    images: [
      "/images/west/swastik-square1.jpg",
      "/images/west/harnav_lavish2.avif",
      "/images/west/vivaan_orbit1.avif"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "Zundal, Ahmedabad",
    PlotArea: "156 Sq. Yards",
    address: "Swastik Square, Zundal, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Swastik Square offers well-planned 2 BHK homes in Zundal, Ahmedabad, designed for comfortable and modern living. With a spacious 156 sq. yard layout, the project provides smartly designed interiors and essential amenities. Priced between ₹57.32 Lakhs to ₹62.60 Lakhs, it is an ideal choice for homebuyers looking for affordability, convenience, and a peaceful residential environment."
  },
  {
    id: 17,
    title: "Imperia Pearl",
    slug: "imperia-pearl",
    price: 6200000,
    displayPrice: "₹62 L",
    image: "/images/west/imperia1.avif",
    images: [
      "/images/west/imperia1.avif",
      "/images/west/imperia2.avif",
      "/images/west/imperia3.avif"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "Zundal, Ahmedabad",
    PlotArea: "168 Sq. Yards",
    address: "Imperia Pearl, Zundal, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Imperia Pearl offers modern 2 BHK homes in the growing residential area of Zundal, Ahmedabad. With a spacious 168 sq. yard layout, the project is designed to provide comfort, functionality, and a contemporary lifestyle. Priced at ₹62 Lakhs, it is an ideal choice for families seeking quality living in a well-connected location."
  },
  {
    id: 18,
    title: "Satyagrah Solitaire",
    slug: "satyagrah-solitaire",
    price: 5250000,
    displayPrice: "₹52.50 L - ₹61 L",
    image: "/images/west/satyagrah_solitaire.avif",
    images: [
      "/images/west/satyagrah_solitaire.avif",
      "/images/west/satyagrah_solitaire2.avif",
      "/images/west/satyagrah_solitaire3.avif"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "Zundal, Ahmedabad",
    PlotArea: "168 Sq. Yards",
    address: "Satyagrah Solitaire, Zundal, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Satyagrah Solitaire offers thoughtfully designed 2 BHK homes in Zundal, Ahmedabad, ideal for modern families. With a spacious 168 sq. yard layout, the project ensures comfort, functionality, and efficient space utilization. Priced between ₹52.50 Lakhs to ₹61 Lakhs, it provides a perfect blend of affordability and contemporary living in a well-connected residential location."
  },
  {
    id: 19,
    title: "The Hive",
    slug: "the-hive",
    price: 6100000,
    displayPrice: "₹61 L",
    image: "/images/west/subh-green.jpeg",
    images: ["/images/west/subh-green.jpeg", "/images/west/omkar.jpeg", "/images/west/vivaan_orbit2.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Zundal - Khoraj, Ahmedabad",
    PlotArea: "159 Sq. Yards",
    address: "The Hive, Zundal - Khoraj, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "The Hive offers modern 2 BHK homes in the emerging residential corridor of Zundal - Khoraj, Ahmedabad. With a well-planned 159 sq. yard layout, the project is designed to provide comfortable and efficient living spaces. Priced at ₹61 Lakhs, it is an excellent option for homebuyers looking for a balance of affordability, connectivity, and contemporary lifestyle."
  },
  {
    id: 20,
    title: "Elevan Angan",
    slug: "elevan-angan",
    price: 6975000,
    displayPrice: "₹69.75 L",
    image: "/images/west/harnav_lavish1.avif",
    images: ["/images/west/harnav_lavish1.avif", "/images/west/omkar.jpeg", "/images/west/subh-green.jpeg"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Gota, Ahmedabad",
    PlotArea: "151 Sq. Yards",
    address: "Elevan Angan, Gota, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Elevan Angan offers thoughtfully designed 2 BHK homes in the well-developed locality of Gota, Ahmedabad. With a spacious 151 sq. yard layout, the project provides a perfect blend of comfort, functionality, and modern living. Priced at ₹69.75 Lakhs, it is an ideal choice for families seeking a well-connected area with quality lifestyle amenities."
  },
  {
    id: 21,
    title: "Solitaire Vista 2",
    slug: "solitaire-vista-2",
    price: 6600000,
    displayPrice: "₹66 L",
    image: "/images/west/omkar.jpeg",
    images: ["/images/west/omkar.jpeg", "/images/west/subh-green.jpeg", "/images/west/harnav_lavish1.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Gota, Ahmedabad",
    PlotArea: "152 Sq. Yards",
    address: "Solitaire Vista 2, Gota, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Solitaire Vista 2 offers modern 2 BHK homes in the prime residential area of Gota, Ahmedabad..."
  },
  {
    id: 22,
    title: "Jaldeep Trident",
    slug: "jaldeep-trident",
    price: 7268000,
    displayPrice: "₹72.68 L",
    image: "/images/west/harnav_lavish3.avif",
    images: ["/images/west/harnav_lavish3.avif", "/images/west/subh-green.jpeg", "/images/west/omkar.jpeg"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Gota, Ahmedabad",
    PlotArea: "162 Sq. Yards",
    address: "Jaldeep Trident, Gota, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Jaldeep Trident offers premium 2 BHK homes in the well-developed locality of Gota, Ahmedabad. With a spacious 162 sq. yard layout, the project is designed to provide modern living with comfort and functionality. Priced at ₹72.68 Lakhs, it is an excellent choice for families looking for quality construction, good connectivity, and a peaceful residential environment."
  },
  {
    id: 23,
    title: "Ideal Ixora",
    slug: "ideal-ixora",
    price: 8450000,
    displayPrice: "₹84.50 L",
    image: "/images/west/omkar.jpeg",
    images: ["/images/west/omkar.jpeg", "/images/west/subh-green.jpeg", "/images/west/vivaan_orbit3.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Chharodi, Ahmedabad",
    PlotArea: "171 Sq. Yards",
    address: "Ideal Ixora, Chharodi, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Ideal Ixora offers premium 2 BHK homes in the fast-developing locality of Chharodi, Ahmedabad. With a spacious 171 sq. yard layout, the project is designed for modern families seeking comfort and convenience. Priced at ₹84.50 Lakhs, it provides a perfect blend of quality construction, connectivity, and a contemporary lifestyle."
  },
  {
    id: 24,
    title: "Aksharth Elegance",
    slug: "aksharth-elegance",
    price: 5950000,
    displayPrice: "₹59.50 L",
    image: "/images/west/subh-green.jpeg",
    images: ["/images/west/subh-green.jpeg", "/images/west/omkar.jpeg", "/images/west/harnav_lavish2.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Godrej Garden City, Ahmedabad",
    PlotArea: "143 Sq. Yards",
    address: "Aksharth Elegance, Godrej Garden City, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Aksharth Elegance offers well-designed 2 BHK homes in the premium township of Godrej Garden City, Ahmedabad. With a spacious 143 sq. yard layout, the project ensures comfortable and modern living. Priced at ₹59.50 Lakhs, it is an ideal choice for families looking for a well-planned community, excellent infrastructure, and a quality lifestyle."
  },
  {
    id: 25,
    title: "Nirvana Abode",
    slug: "nirvana-abode",
    price: 6327000,
    displayPrice: "₹63.27 L",
    image: "/images/west/omkar.jpeg",
    images: ["/images/west/omkar.jpeg", "/images/west/subh-green.jpeg", "/images/west/imperia1.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Godrej Garden City, Ahmedabad",
    PlotArea: "160 Sq. Yards",
    address: "Nirvana Abode, Godrej Garden City, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Nirvana Abode offers thoughtfully designed 2 BHK homes in the premium township of Godrej Garden City, Ahmedabad. With a spacious 160 sq. yard layout, the project ensures comfortable and modern living for families. Priced at ₹63.27 Lakhs, and with possession expected by December 2026, it is an excellent choice for homebuyers seeking a future-ready home in a well-planned community."
  },
  {
    id: 26,
    title: "Shlok 99",
    slug: "shlok-99",
    price: 5900000,
    displayPrice: "₹59 L - ₹60 L",
    image: "/images/west/subh-green.jpeg",
    images: ["/images/west/subh-green.jpeg", "/images/west/omkar.jpeg", "/images/west/imperia2.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Godrej Garden City, Ahmedabad",
    PlotArea: "148 - 151 Sq. Yards",
    address: "Shlok 99, Godrej Garden City, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Shlok 99 offers well-planned 2 BHK homes in the premium township of Godrej Garden City, Ahmedabad. With size options ranging from 148 to 151 sq. yards, the project is designed to provide comfort, functionality, and modern living. Priced between ₹59 Lakhs to ₹60 Lakhs, it is an ideal choice for families looking for affordability within a well-developed and connected community."
  },
  {
    id: 27,
    title: "57 Park",
    slug: "57-park",
    price: 6564000,
    displayPrice: "₹65.64 L",
    image: "/images/east/sahajanand-exotica.jpeg",
    images: ["/images/east/sahajanand-exotica.jpeg", "/images/west/subh-green.jpeg", "/images/west/kb_royal1.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Godrej Garden City, Ahmedabad",
    PlotArea: "153 Sq. Yards",
    address: "57 Park, Godrej Garden City, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "57 Park offers thoughtfully designed 2 BHK homes in the well-planned township of Godrej Garden City, Ahmedabad. With a spacious 153 sq. yard layout, the project ensures comfortable and modern living for families. Priced at ₹65.64 Lakhs, it is an excellent choice for homebuyers seeking quality construction, good connectivity, and a premium residential environment."
  },
  {
    id: 28,
    title: "Scarlet Springs",
    slug: "scarlet-springs",
    price: 6022000,
    displayPrice: "₹60.22 L",
    image: "/images/east/Swara.jpeg",
    images: ["/images/west/harnav_lavish2.avif", "/images/west/subh-green.jpeg", "/images/west/kb_royal2.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "New Ranip, Ahmedabad",
    PlotArea: "141 Sq. Yards",
    address: "Scarlet Springs, New Ranip, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Scarlet Springs offers thoughtfully designed 2 BHK homes in the developing locality of New Ranip, Ahmedabad. With a well-planned 141 sq. yard layout, the project ensures comfortable and modern living for families. Priced at ₹60.22 Lakhs, it is an ideal choice for homebuyers looking for affordability, connectivity, and a peaceful residential environment."
  },
  {
    id: 29,
    title: "Rajshree Green Park",
    slug: "rajshree-green-park",
    price: 5800000,
    displayPrice: "₹58 L - ₹59 L",
    image: "/images/east/Eleven.jpeg",
    images: ["/images/east/Eleven.jpeg", "/images/west/subh-green.jpeg", "/images/west/satyagrah_solitaire.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "New Ranip, Ahmedabad",
    PlotArea: "145 - 148 Sq. Yards",
    address: "Rajshree Green Park, New Ranip, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Rajshree Green Park offers well-designed 2 BHK homes in the developing area of New Ranip, Ahmedabad. With size options ranging from 145 to 148 sq. yards, the project provides comfortable and efficient living spaces for modern families. Priced between ₹58 Lakhs to ₹59 Lakhs, it is an ideal choice for homebuyers seeking affordability along with good connectivity and a peaceful residential environment."
  },
  {
    id: 30,
    title: "Vinayak Elegance",
    slug: "vinayak-elegance",
    price: 7500000,
    displayPrice: "₹75 L",
    image: "/images/east/Sahajanand-harmony.jpeg",
    images: ["/images/east/Sahajanand-harmony.jpeg", "/images/west/subh-green.jpeg", "/images/west/satyagrah_solitaire2.avif"],
    status: "Under Construction",
    bedrooms: 2,
    location: "Nava Vadaj, Ahmedabad",
    PlotArea: "N/A",
    address: "Vinayak Elegance, Nava Vadaj, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Vinayak Elegance offers modern 2 BHK homes in the well-connected locality of Nava Vadaj, Ahmedabad. Designed for comfortable and contemporary living, the project is ideal for families seeking convenience and quality construction."
  },
  {
    id: 31,
    title: "Sahajanand Atman",
    slug: "sahajanand-atman",
    price: 5450000,
    displayPrice: "₹54.50 L - ₹55.50 L",
    image: "/images/east/Sanrise-home.jpeg",
    images: [
      "/images/east/Sanrise-home.jpeg",
      "/images/east/Sahajanand-harmony.jpeg",
      "/images/east/Anusthan.jpeg"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "New Chandkheda, Ahmedabad",
    PlotArea: "152 - 156 Sq. Yards",
    address: "Sahajanand Atman, New Chandkheda, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Sahajanand Atman offers thoughtfully designed 2 BHK homes in the fast-developing locality of New Chandkheda, Ahmedabad. With size options ranging from 152 to 156 sq. yards, the project provides comfortable and modern living spaces for families. Priced between ₹54.50 Lakhs to ₹55.50 Lakhs, it is an excellent choice for homebuyers seeking affordability, connectivity, and a peaceful residential environment."
  },
  {
    id: 32,
    title: "Saral Serenity",
    slug: "saral-serenity",
    price: 5550000,
    displayPrice: "₹55.50 L - ₹57.50 L",
    image: "/images/east/Sahajanand-harmony.jpeg",
    images: [
      "/images/east/Sahajanand-harmony.jpeg",
      "/images/east/sahajanand-exotica.jpeg",
      "/images/east/Sanrise-home.jpeg"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "New Chandkheda, Ahmedabad",
    PlotArea: "142 - 146 Sq. Yards",
    address: "Saral Serenity, New Chandkheda, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Saral Serenity offers well-designed 2 BHK homes in the growing locality of New Chandkheda, Ahmedabad. With size options ranging from 142 to 146 sq. yards, the project provides comfortable and efficient living spaces for modern families. Priced between ₹55.50 Lakhs to ₹57.50 Lakhs, it is an ideal choice for homebuyers looking for affordability along with good connectivity and a peaceful residential environment."
  },
  {
    id: 33,
    title: "Sanidhya Suvas",
    slug: "sanidhya-suvas",
    price: 4850000,
    displayPrice: "₹48.50 L - ₹52 L",
    image: "/images/east/Sanrise-home.jpeg",
    images: [
      "/images/east/Sanrise-home.jpeg",
      "/images/east/sona-sidhhi.jpeg",
      "/images/east/Eleven.jpeg"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "New Chandkheda, Ahmedabad",
    PlotArea: "142 - 152 Sq. Yards",
    address: "Sanidhya Suvas, New Chandkheda, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Sanidhya Suvas offers thoughtfully designed 2 BHK homes in the fast-developing locality of New Chandkheda, Ahmedabad. With multiple size options ranging from 142 to 152 sq. yards, the project caters to different family needs. Priced between ₹48.50 Lakhs to ₹52 Lakhs, it is an ideal choice for homebuyers seeking affordability, comfort, and a well-connected residential environment."
  },
  {
    id: 34,
    title: "Orium Elements",
    slug: "orium-elements",
    price: 6200000,
    displayPrice: "₹62 L - ₹69 L",
    image: "/images/east/Eleven.jpeg",
    images: [
      "/images/east/Eleven.jpeg",
      "/images/east/Avalon-DHS.jpeg",
      "/images/west/harnav_lavish2.avif"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "New Chandkheda, Ahmedabad",
    PlotArea: "160 - 175 Sq. Yards",
    address: "Orium Elements, New Chandkheda, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Orium Elements offers premium 2 BHK homes in the developing locality of New Chandkheda, Ahmedabad. With multiple size options ranging from 160 to 175 sq. yards, the project is designed to provide spacious and comfortable living for modern families. Priced between ₹62 Lakhs to ₹69 Lakhs, it is an excellent choice for homebuyers seeking a balance of luxury, connectivity, and affordability."
  },
  {
    id: 35,
    title: "Hari Om Sapphire",
    slug: "hari-om-sapphire",
    price: 6283000,
    displayPrice: "₹62.83 L",
    image: "/images/west/vivaan_orbit1.avif",
    images: [
      "/images/west/vivaan_orbit1.avif",
      "/images/west/vivaan_orbit2.avif",
      "/images/west/vivaan_orbit3.avif"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "Ognaj, Ahmedabad",
    PlotArea: "150 Sq. Yards",
    address: "Hari Om Sapphire, Ognaj, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Hari Om Sapphire offers modern 2 BHK homes in the developing locality of Ognaj, Ahmedabad. With a spacious 150 sq. yard layout, the project is designed to provide comfortable and efficient living for families. Priced at ₹62.83 Lakhs, it is an ideal choice for homebuyers seeking a balance of affordability, connectivity, and contemporary lifestyle."
  },
  {
    id: 36,
    title: "SVS Highness",
    slug: "svs-highness",
    price: 6300000,
    displayPrice: "₹63 L - ₹81 L | ₹95 L (Penthouse)",
    image: "/images/east/Swara.jpeg",
    images: [
      "/images/west/harnav_lavish2.avif",
      "/images/east/Anusthan.jpeg",
      "/images/east/AARADHANA_2.jpeg"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "Nava Vadaj, Ahmedabad",
    PlotArea: "133 - 163 Sq. Yards",
    address: "SVS Highness, Nava Vadaj, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "SVS Highness offers a wide range of 2 BHK homes in the prime locality of Nava Vadaj, Ahmedabad, along with exclusive penthouse options. With multiple size configurations ranging from 133 to 163 sq. yards, the project caters to diverse lifestyle needs. Priced between ₹63 Lakhs to ₹81 Lakhs, and ₹95 Lakhs for penthouses, it is an ideal choice for homebuyers seeking flexibility, modern living, and excellent connectivity."
  },
  {
    id: 37,
    title: "Nirman Sahvas",
    slug: "nirman-sahvas",
    price: 5351000,
    displayPrice: "₹53.51 L",
    image: "/images/east/Avalon-DHS.jpeg",
    images: [
      "/images/east/Avalon-DHS.jpeg",
      "/images/east/Anusthan.jpeg",
      "/images/east/AARADHANA_2.jpeg"
    ],
    status: "Under Construction",
    bedrooms: 2,
    location: "Adalaj, Ahmedabad",
    PlotArea: "150 Sq. Yards",
    address: "Nirman Sahvas, Adalaj, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Nirman Sahvas offers thoughtfully designed 2 BHK homes in the peaceful locality of Adalaj, Ahmedabad. With a spacious 150 sq. yard layout, the project ensures comfortable and modern living for families. Priced at ₹53.51 Lakhs, it is an ideal choice for homebuyers looking for affordability, connectivity, and a serene residential environment."
  },
  {
    id: 38,
    title: "Ratnamani - Trident Extria",
    slug: "ratnamani-trident-extria",
    price: 7200000,
    displayPrice: "₹72 L (Down Payment) - ₹76 L",
    image: "/images/east/Anusthan.jpeg",
    images: [
      "/images/east/Anusthan.jpeg",
      "/images/east/AARADHANA_2.jpeg",
      "/images/west/harnav_lavish2.avif"
    ],
    status: "Under Construction",
    bedrooms: 3,
    location: "Vaishnodevi, Ahmedabad",
    PlotArea: "200 Sq. Yards",
    address: "Ratnamani - Trident Extria, Vaishnodevi, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Ratnamani - Trident Extria offers spacious 3 BHK homes in the prime locality of Vaishnodevi, Ahmedabad. With a well-planned 200 sq. yard layout, the project is designed for modern families seeking comfort and premium living. Priced at ₹76 Lakhs with attractive down payment options starting from ₹72 Lakhs, it is an excellent choice for homebuyers looking for value, connectivity, and quality construction."
  },
  {
    id: 39,
    title: "Royal Opulence",
    slug: "royal-opulence",
    price: 8340000,
    displayPrice: "₹83.40 L",
    image: "/images/west/royal-crown1.avif",
    images: [
      "/images/west/royal-crown1.avif",
      "/images/west/royal-crown2.avif",
      "/images/west/royal-crown3.avif"
    ],
    status: "Under Construction",
    bedrooms: 3,
    location: "Vaishnodevi, Ahmedabad",
    PlotArea: "200 Sq. Yards",
    address: "Royal Opulence, Vaishnodevi, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Royal Opulence offers premium 3 BHK homes in the prime locality of Vaishnodevi, Ahmedabad. With a spacious 200 sq. yard layout, the project is designed to deliver luxury, comfort, and modern living. Priced at ₹83.40 Lakhs, it is an ideal choice for families seeking a high-quality lifestyle with excellent connectivity and well-developed surroundings."
  },
  {
    id: 40,
    title: "Satatya Syril - II",
    slug: "satatya-syril-ii",
    price: 13300000,
    displayPrice: "₹1.33 Cr - ₹1.45 Cr",
    image: "/images/west/satyagrah_solitaire.avif",
    images: [
      "/images/west/satyagrah_solitaire.avif",
      "/images/west/satyagrah_solitaire2.avif",
      "/images/west/satyagrah_solitaire3.avif"
    ],
    status: "Under Construction",
    bedrooms: 3,
    location: "Vaishnodevi, Ahmedabad",
    PlotArea: "261 - 276 Sq. Yards",
    address: "Satatya Syril - II, Vaishnodevi, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Satatya Syril - II offers spacious 3 BHK homes in the prime locality of Vaishnodevi, Ahmedabad. With layouts ranging from 261 to 276 sq. yards, this premium project provides modern living with comfort and luxury. Priced between ₹1.33 Cr to ₹1.45 Cr, it is perfect for families seeking high-end homes with excellent connectivity and top-notch amenities."
  },
  {
    id: 41,
    title: "Terra Sky",
    slug: "terra-sky",
    price: 8800000,
    displayPrice: "₹88 L - ₹91.50 L",
    image: "/images/west/royal-crown1.avif",
    images: [
      "/images/west/royal-crown1.avif",
      "/images/west/royal-crown2.avif",
      "/images/west/royal-crown3.avif"
    ],
    status: "Under Construction",
    bedrooms: 3,
    location: "Zundal, Ahmedabad",
    PlotArea: "235 - 245 Sq. Yards",
    address: "Terra Sky, Zundal, Ahmedabad",
    featured: true,
    zone: "West",
    description:
      "Terra Sky offers premium 3 BHK homes in the well-connected locality of Zundal, Ahmedabad. With layouts ranging from 235 to 245 sq. yards, the project is designed for families seeking spacious and modern living. Priced between ₹88 Lakhs to ₹91.50 Lakhs, it is an excellent choice for homebuyers looking for quality construction, comfort, and excellent connectivity."
  },
  {
    id: 42,
    title: "Stellavia",
    slug: "stellavia",
    price: 8500000,
    displayPrice: "₹85 L",
    image: "/images/west/kb_royal1.avif",
    images: ["/images/west/kb_royal1.avif", "/images/west/kb_royal2.avif", "/images/west/kb_royal3.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Khoraj, Ahmedabad",
    PlotArea: "215 Sq. Yards",
    address: "Stellavia, Khoraj, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Stellavia offers spacious 3 BHK homes in Khoraj, Ahmedabad, with 215 sq. yard layouts. Priced at ₹85 Lakhs, it is perfect for families seeking comfort, quality, and connectivity."
  },
  {
    id: 43,
    title: "Alaya Belmonte",
    slug: "alaya-belmonte",
    price: 9870000,
    displayPrice: "₹98.7 L",
    image: "/images/west/vivaan_orbit1.avif",
    images: ["/images/west/vivaan_orbit1.avif", "/images/west/vivaan_orbit2.avif", "/images/west/vivaan_orbit3.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Chharodi, Ahmedabad",
    PlotArea: "210 Sq. Yards",
    address: "Alaya Belmonte, Chharodi, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Alaya Belmonte offers premium 3 BHK homes in Chharodi, Ahmedabad, with a 210 sq. yard layout. Priced at ₹98.7 Lakhs, it combines modern design, comfort, and connectivity."
  },
  {
    id: 44,
    title: "The Q",
    slug: "the-q",
    price: 12200000,
    displayPrice: "₹1.12 Cr - ₹1.22 Cr",
    image: "/images/east/Anusthan.jpeg",
    images: ["/images/east/Anusthan.jpeg", "/images/east/AARADHANA_2.jpeg", "/images/east/Avalon-DHS.jpeg"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Chharodi, Ahmedabad",
    PlotArea: "223 - 235 Sq. Yards",
    address: "The Q, Chharodi, Ahmedabad",
    featured: true,
    zone: "West",
    description: "The Q offers premium 3 BHK homes in Chharodi, Ahmedabad, with layouts ranging from 223 to 235 sq. yards. Priced between ₹1.12 Cr to ₹1.22 Cr, it provides luxury living with excellent connectivity."
  },
  {
    id: 45,
    title: "Rajshree Regelia",
    slug: "rajshree-regelia",
    price: 13100000,
    displayPrice: "₹1.31 Cr - ₹1.34 Cr",
    image: "/images/east/sahajanand-exotica.jpeg",
    images: ["/images/east/sahajanand-exotica.jpeg", "/images/east/Sahajanand-harmony.jpeg", "/images/west/harnav_lavish2.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Chharodi, Ahmedabad",
    PlotArea: "257 - 263 Sq. Yards",
    address: "Rajshree Regelia, Chharodi, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Rajshree Regelia offers premium 3 BHK homes in Chharodi, Ahmedabad, with layouts from 257 to 263 sq. yards. Priced between ₹1.31 Cr to ₹1.34 Cr, it is ideal for families seeking luxury and comfort."
  },
  {
    id: 46,
    title: "Blubell",
    slug: "blubell",
    price: 11100000,
    displayPrice: "₹1.11 Cr - ₹1.22 Cr",
    image: "/images/west/kb_royal1.avif",
    images: ["/images/west/kb_royal1.avif", "/images/west/kb_royal2.avif", "/images/west/kb_royal3.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Jagatpur, Ahmedabad",
    PlotArea: "215 - 238 Sq. Yards",
    address: "Blubell, Jagatpur, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Blubell offers spacious 3 BHK homes in Jagatpur, Ahmedabad, with layouts from 215 to 238 sq. yards. Priced between ₹1.11 Cr to ₹1.22 Cr, perfect for families seeking premium living."
  },
  {
    id: 47,
    title: "Sidharth Green",
    slug: "sidharth-green",
    price: 12700000,
    displayPrice: "₹1.27 Cr - ₹1.31 Cr",
    image: "/images/west/imperia1.avif",
    images: ["/images/west/imperia1.avif", "/images/west/imperia2.avif", "/images/west/imperia3.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Gota, Ahmedabad",
    PlotArea: "283 - 293 Sq. Yards",
    address: "Sidharth Green, Gota, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Sidharth Green offers premium 3 BHK homes in Gota, Ahmedabad, with layouts from 283 to 293 sq. yards. Priced between ₹1.27 Cr to ₹1.31 Cr, it combines luxury, space, and connectivity."
  },
  {
    id: 48,
    title: "Aditya Altuss",
    slug: "aditya-altuss",
    price: 11200000,
    displayPrice: "₹1.12 Cr - ₹1.20 Cr",
    image: "/images/west/harnav_lavish1.avif",
    images: ["/images/west/harnav_lavish1.avif", "/images/west/harnav_lavish2.avif", "/images/west/harnav_lavish3.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Jagatpur, Ahmedabad",
    PlotArea: "222 - 244 Sq. Yards",
    address: "Aditya Altuss, Jagatpur, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Aditya Altuss offers modern 3 BHK homes in Jagatpur, Ahmedabad, with layouts from 222 to 244 sq. yards. Priced between ₹1.12 Cr to ₹1.20 Cr, ideal for families seeking comfort and quality."
  },
  {
    id: 49,
    title: "Dharti Skyline",
    slug: "dharti-skyline",
    price: 8500000,
    displayPrice: "₹85 L",
    image: "/images/west/vivaan_orbit3.avif",
    images: ["/images/west/vivaan_orbit3.avif", "/images/west/vivaan_orbit1.avif", "/images/west/vivaan_orbit2.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Godrej Garden City, Ahmedabad",
    PlotArea: "180 - 200 Sq. Yards",
    address: "Dharti Skyline, Godrej Garden City, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Dharti Skyline offers 3 BHK homes in Godrej Garden City, Ahmedabad, with layouts from 180 to 200 sq. yards. Priced at ₹85 L, it is perfect for homebuyers seeking modern living in a connected community."
  },
  {
    id: 50,
    title: "Aspire",
    slug: "aspire",
    price: 8100000,
    displayPrice: "₹81 L",
    image: "/images/west/imperia2.avif",
    images: ["/images/west/imperia2.avif", "/images/west/imperia1.avif", "/images/west/imperia3.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Tragadh, Ahmedabad",
    PlotArea: "210 Sq. Yards",
    address: "Aspire, Tragadh, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Aspire offers 3 BHK homes in Tragadh, Ahmedabad, with a 210 sq. yard layout. Priced at ₹81 L, perfect for families seeking premium, modern living."
  },
  {
    id: 51,
    title: "Signate",
    slug: "signate",
    price: 8650000,
    displayPrice: "₹86.50 L - ₹1.10 Cr",
    image: "/images/west/kb_royal3.avif",
    images: ["/images/west/kb_royal3.avif", "/images/west/kb_royal1.avif", "/images/west/kb_royal2.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "New Ranip, Ahmedabad",
    PlotArea: "200 - 243 Sq. Yards",
    address: "Signate, New Ranip, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Signate offers spacious 3 BHK homes in New Ranip, Ahmedabad, with layouts from 200 to 243 sq. yards. Prices range from ₹86.50 L to ₹1.10 Cr, ideal for premium living and connectivity."
  },
  {
    id: 52,
    title: "Swam Residencia",
    slug: "swam-residencia",
    price: 9000000,
    displayPrice: "₹90 L",
    image: "/images/west/royal-crown3.avif",
    images: ["/images/west/royal-crown3.avif", "/images/west/royal-crown1.avif", "/images/west/royal-crown2.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Sola, Ahmedabad",
    PlotArea: "196 Sq. Yards",
    address: "Swam Residencia, Sola, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Swam Residencia offers 3 BHK homes in Sola, Ahmedabad, with a 196 sq. yard layout. Priced at ₹90 L, perfect for families seeking modern living with comfort and connectivity."
  },
  {
    id: 54,
    title: "Festival Vibes",
    slug: "festival-vibes",
    price: 9900000,
    displayPrice: "₹99 L",
    image: "/images/west/harnav_lavish3.avif",
    images: ["/images/west/harnav_lavish3.avif", "/images/west/harnav_lavish1.avif", "/images/west/harnav_lavish2.avif"],
    status: "Under Construction",
    bedrooms: 3,
    location: "Sola, Ahmedabad",
    PlotArea: "203 Sq. Yards",
    address: "Festival Vibes, Sola, Ahmedabad",
    featured: true,
    zone: "West",
    description: "Festival Vibes offers 3 BHK homes in Sola, Ahmedabad, with a 203 sq. yard layout. Priced at ₹99 L, it provides premium living with spacious layouts and excellent connectivity."
  }

];
